// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BloodDonationSystem.Repositories.HungHK.Models;

public partial class ReportsHungHk
{
    public int ReportHungHkid { get; set; }

    public DateOnly? ReportDate { get; set; }

    public int? ReportTypeId { get; set; }

    public int? TotalUsers { get; set; }

    public int? TotalDonors { get; set; }

    public int? TotalRecipients { get; set; }

    public int? TotalBloodUnits { get; set; }

    public int? TotalRequests { get; set; }

    public int? TotalDonations { get; set; }

    public string MostNeededBloodType { get; set; }

    public bool? Status { get; set; }

    public int? GeneratedBy { get; set; }

    public virtual SystemUserAccount GeneratedByNavigation { get; set; }

    public virtual ReportTypesHungHk ReportType { get; set; }
}