// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BloodDonationSystem.Repositories.HungHK.Models;

public partial class ReportTypesHungHk
{
    public int ReportTypeHungHkid { get; set; }

    public string TypeName { get; set; }

    public string Description { get; set; }
    [JsonIgnore]
    public virtual ICollection<ReportsHungHk> ReportsHungHks { get; set; } = new List<ReportsHungHk>();
}